import type {GameAction,GameState,VideoProject} from '../types/game';
const clamp=(n:number,a:number,b:number)=>Math.min(b,Math.max(a,n));
const notify=(s:GameState,m:string,type:'success'|'error'|'info'='info')=>{s.notifications=[...s.notifications,{id:String(Date.now()+Math.random()),message:m,type}].slice(-5)};
const advance=(s:GameState,h:number)=>{const d=new Date(s.time.date+'T00:00:00');let x=s.time.hour+h;while(x>=24){x-=24;d.setDate(d.getDate()+1)}s.time={date:d.toISOString().slice(0,10),hour:x};s.creator.week=Math.floor((Date.parse(s.time.date)-Date.parse('2026-09-03'))/604800000)+1};
const world=(s:GameState,h:number)=>{const days=h/24;s.worldCreators=s.worldCreators.map(c=>({...c,subscribers:Math.round(c.subscribers*(1+c.growthRate*days*(.9+Math.random()*.2)))}));s.trends=s.trends.map(t=>({...t,intensity:Math.max(1,t.intensity-h/Math.max(24,t.lifetimeHours)*.35),lifetimeHours:t.lifetimeHours-h})).filter(t=>t.lifetimeHours>0);s.pendingRevenue+=s.creator.subscribers*.00002*h};
const projectWork=(s:GameState,h:number)=>{s.projects=s.projects.map(p=>{const u=Math.min(h,Math.max(0,p.totalHours-p.hoursDone));return {...p,hoursDone:p.hoursDone+u,quality:clamp(p.quality+u*1.5,0,100)}})};
const create=(s:GameState,a:Extract<GameAction,{type:'CREATE_PROJECT'}>)=>{if(s.creator.energy<15){notify(s,'Pas assez d’énergie.','error');return s}const total=a.format==='documentary'?24:a.format==='short'?4:a.format==='live'?3:10;const p:VideoProject={id:String(Date.now()),title:a.title.trim(),category:a.category,format:a.format,language:a.language,isFeat:false,isSeries:false,imageStock:a.imageStock,totalHours:total,hoursDone:0,quality:15,hype:0,tasks:[],published:false,totalTurnsRequired:Math.ceil(total/8),turnsSpent:0,isReadyToPublish:false};s.creator.energy-=15;s.projects.push(p);notify(s,'Projet créé.','success');return s};
const publish=(s:GameState,id:string)=>{const p=s.projects.find(x=>x.id===id);if(!p||p.hoursDone<p.totalHours)return s;const t=s.trends.find(x=>x.category===p.category);const l=s.audience.find(x=>x.interests.includes(p.category))?.loyalty??5;const views=Math.max(50,Math.round(s.creator.subscribers*(.15+l/100)*(.55+p.quality/100)*(t?.intensity??1)*(.75+Math.random()*.7)));const gained=Math.max(1,Math.round(views*(.006+s.reputationStats.trust/5000)));const revenue=views*(p.format==='short'?.00002:.0008);s.creator.subscribers+=gained;s.pendingRevenue+=revenue;s.reputationStats.popularity=clamp(s.reputationStats.popularity+(views>s.creator.subscribers?1:.2),0,100);s.reputationStats.credibility=clamp(s.reputationStats.credibility+p.quality/300,0,100);s.publishedVideos.unshift({id:String(Date.now()),projectId:p.id,title:p.title,category:p.category,format:p.format,thumbnail:p.imageStock,views,subscribersGained:gained,revenueGenerated:revenue,publishedAt:s.time.date,week:s.creator.week});s.projects=s.projects.filter(x=>x.id!==id);notify(s,'Vidéo publiée : '+views.toLocaleString('fr-FR')+' vues, +'+gained.toLocaleString('fr-FR')+' abonnés.','success');return s};
export const reduceGame=(state:GameState,a:GameAction)=>{const s=structuredClone(state);switch(a.type){case'REST':advance(s,24);s.time.hour=8;s.creator.energy=s.creator.maxEnergy;s.creator.stress=clamp(s.creator.stress-20,0,100);world(s,24);notify(s,'Journée de repos terminée.','success');return s;case'SLEEP':advance(s,8);s.creator.energy=clamp(s.creator.energy+80,0,s.creator.maxEnergy);s.creator.stress=clamp(s.creator.stress-12,0,100);world(s,8);return s;case'WORK':if(s.creator.energy<a.hours*5){notify(s,'Tu es trop fatigué.','error');return s}advance(s,a.hours);s.creator.energy-=a.hours*5;s.creator.stress=clamp(s.creator.stress+a.hours*.8,0,100);projectWork(s,a.hours);world(s,a.hours);return s;case'CREATE_PROJECT':return create(s,a);case'PUBLISH_VIDEO':return publish(s,a.projectId)}};
