import type { BusinessContract, BusinessOffer, CreatorProfile, Equipment } from '../types/game';

export default function AgencyScreen({creator,equipment,offers,contracts,acceptOffer}:{creator:CreatorProfile;equipment:Equipment;offers:BusinessOffer[];contracts:BusinessContract[];acceptOffer:(id:string)=>void}){
  return <div className="space-y-5">
    <div><h1 className="text-xl font-bold">Business</h1><p className="mt-1 text-[11px] text-zinc-500">Ta boîte mail professionnelle et tes opportunités.</p></div>
    <section className="rounded-2xl border border-white/10 bg-[#181818] p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">Boîte de réception</p><p className="text-[10px] text-zinc-500">Sponsors, agences, collaborations</p></div><span className="rounded-full bg-white px-2 py-1 text-[9px] font-bold text-black">{offers.filter(o=>creator.subscribers>=o.minSubscribers).length} nouvelles</span></div></section>
    {contracts.length>0&&<section className="space-y-2"><div><h2 className="text-sm font-bold">Contrats</h2><p className="text-[10px] text-zinc-500">Objectifs, délais et partenariats signés.</p></div>{contracts.map(c=>{const percent=c.target>0?Math.round(c.progress/c.target*100):0;const tone=c.status==='active'?'emerald':c.status==='completed'?'sky':'red';return <article key={c.id} className={`rounded-xl border p-3 ${tone==='emerald'?'border-emerald-500/20 bg-emerald-500/5':tone==='sky'?'border-sky-500/20 bg-sky-500/5':'border-red-500/20 bg-red-500/5'}`}><div className="flex items-center justify-between"><span className="text-[10px] uppercase text-zinc-400">{c.type}</span><span className="rounded-full bg-white/10 px-2 py-1 text-[9px] font-bold">{c.status==='active'?'ACTIF':c.status==='completed'?'TERMINÉ':'ÉCHOUÉ'}</span></div><h3 className="mt-2 text-xs font-bold">{c.company}</h3><p className="mt-1 text-[11px] text-zinc-300">{c.title}</p>{c.objective!=='none'&&<div className="mt-3"><div className="mb-1 flex justify-between text-[9px] text-zinc-500"><span>{c.objective==='publish'?'Publier une vidéo':'Vues depuis la signature'}</span><span>{c.progress.toLocaleString('fr-FR')} / {c.target.toLocaleString('fr-FR')}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-white transition-all" style={{width:`${Math.min(100,percent)}%`}}/></div></div>}<div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-zinc-500">{c.amount!==undefined&&<span>+{c.amount.toLocaleString('fr-FR')} €</span>}{c.commission!==undefined&&<span>{c.commission} % commission</span>}<span>{c.weeksElapsed}/{c.durationWeeks} semaines</span><span>Signé le {new Date(c.signedAt+'T00:00:00').toLocaleDateString('fr-FR')}</span></div></article>})}</section>}
    <div className="space-y-2">{offers.length===0?<div className="rounded-xl border border-white/10 bg-[#181818] p-4 text-center text-[10px] text-zinc-500">Aucune nouvelle offre pour le moment.</div>:offers.map(o=>{const unlocked=creator.subscribers>=o.minSubscribers;return <article key={o.id} className={`rounded-xl border p-3 ${unlocked?'border-white/10 bg-[#181818]':'border-white/5 bg-black opacity-40'}`}><div className="flex justify-between"><span className="text-[10px] uppercase text-zinc-500">{o.type}</span><span className="text-[9px] text-zinc-600">{o.minSubscribers.toLocaleString('fr-FR')} abonnés requis</span></div><h3 className="mt-2 text-xs font-bold">{o.company}</h3><p className="mt-1 text-[11px] text-zinc-300">{o.title}</p>{o.amount!==undefined&&<p className="mt-2 text-xs font-bold">{o.amount.toLocaleString('fr-FR')} €</p>}{o.commission!==undefined&&<p className="mt-2 text-xs font-bold">{o.commission} %</p>}{unlocked?<button onClick={()=>acceptOffer(o.id)} className="mt-3 w-full rounded-lg bg-white py-2 text-[10px] font-bold text-black">Accepter l'offre</button>:<p className="mt-2 text-[9px] text-zinc-600">Offre verrouillée</p>}</article>})}</div>
    <section className="rounded-xl border border-white/10 bg-[#181818] p-3"><h2 className="text-xs font-bold">Setup actuel</h2><div className="mt-2 grid grid-cols-3 gap-2 text-[10px] text-zinc-500"><span>Caméra <b className="text-white">Niv. {equipment.cameraLevel}</b></span><span>Micro <b className="text-white">Niv. {equipment.micLevel}</b></span><span>PC <b className="text-white">Niv. {equipment.pcLevel}</b></span></div></section>
  </div>
}