import {useState} from 'react';
import type {CreatorProfile,Playlist,PublishedVideo,Series,ChannelTab} from '../types/game';
export default function ChannelScreen({creator,videos,playlists,series,createPlaylist,addToPlaylist}:{creator:CreatorProfile;videos:PublishedVideo[];playlists:Playlist[];series:Series[];createPlaylist:(title:string,description:string)=>void;addToPlaylist:(playlistId:string,videoId:string)=>void}){
 const [tab,setTab]=useState<ChannelTab>('home'); const [newList,setNewList]=useState(''); const [description,setDescription]=useState('');
 return <div className="space-y-4">
  <section className="overflow-hidden rounded-2xl border border-white/10 bg-[#181818]"><div className="h-24 bg-gradient-to-r from-zinc-900 via-zinc-800 to-zinc-950"/><div className="px-4 pb-4"><div className="-mt-7 grid h-14 w-14 place-items-center rounded-full border-4 border-[#181818] bg-[#272727] text-lg font-black">{creator.name.slice(0,1).toUpperCase()}</div><h1 className="mt-2 text-xl font-bold">{creator.name}</h1><p className="text-[10px] text-zinc-500">@{creator.name.toLowerCase()} · {creator.subscribers.toLocaleString('fr-FR')} abonnés</p><p className="mt-2 text-xs text-zinc-300">Créateur virtuel · Semaine {creator.week}</p></div><div className="grid grid-cols-4 border-t border-white/10">{(['home','videos','playlists','about'] as ChannelTab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`py-3 text-[10px] font-bold ${tab===t?'border-b-2 border-white text-white':'text-zinc-500'}`}>{t==='home'?'Accueil':t==='videos'?'Vidéos':t==='playlists'?'Playlists':'À propos'}</button>)}</div></section>
  {tab==='home'&&<><section><h2 className="mb-2 text-sm font-bold">Dernières vidéos</h2><div className="grid grid-cols-2 gap-3">{videos.slice(0,4).map(v=><article key={v.id}><img src={v.thumbnail} className="aspect-video w-full rounded-lg object-cover"/><p className="mt-1 line-clamp-2 text-[11px] font-semibold">{v.title}</p><p className="text-[9px] text-zinc-500">{v.views.toLocaleString('fr-FR')} vues · +{v.subscribersGained} abonnés</p></article>)}{videos.length===0&&<p className="text-xs text-zinc-500">Publie ta première vidéo depuis le Studio.</p>}</div></section><section><h2 className="mb-2 text-sm font-bold">Séries</h2>{series.length?series.map(s=><div key={s.id} className="rounded-xl border border-white/10 bg-[#181818] p-3"><div className="flex justify-between"><b className="text-xs">{s.name}</b><span className="text-[9px] text-zinc-500">{s.episodeCount} épisode{s.episodeCount>1?'s':''}</span></div><p className="mt-1 text-[10px] text-zinc-500">Popularité {Math.round(s.popularity)} · Fidélité {Math.round(s.loyalty)} · Attente {Math.round(s.expectation)}</p></div>):<p className="text-xs text-zinc-500">Tes séries apparaîtront ici.</p>}</section></>}
  {tab==='videos'&&<section className="space-y-3">{videos.map(v=><article key={v.id} className="flex gap-3 rounded-xl border border-white/10 bg-[#181818] p-2"><img src={v.thumbnail} className="h-20 w-32 rounded-lg object-cover"/><div className="min-w-0 flex-1"><p className="text-xs font-bold">{v.title}</p><p className="mt-1 text-[10px] text-zinc-500">{v.views.toLocaleString('fr-FR')} vues · semaine {v.week}</p><select onChange={e=>e.target.value&&addToPlaylist(e.target.value,v.id)} defaultValue="" className="mt-2 w-full rounded-md border border-white/10 bg-black p-1.5 text-[9px]"><option value="">Ajouter à une playlist…</option>{playlists.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div></article>)}</section>}
  {tab==='playlists'&&<section className="space-y-3"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input value={newList} onChange={e=>setNewList(e.target.value)} placeholder="Nom de la playlist" className="rounded-lg border border-white/10 bg-black p-2 text-xs"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description (optionnelle)" className="rounded-lg border border-white/10 bg-black p-2 text-xs"/><button disabled={!newList.trim()} onClick={()=>{createPlaylist(newList.trim(),description.trim());setNewList('');setDescription('')}} className="rounded-lg bg-white px-3 text-[10px] font-bold text-black disabled:opacity-40">Créer</button></div>{playlists.map(p=><article key={p.id} className="rounded-xl border border-white/10 bg-[#181818] p-3"><div className="flex justify-between"><div><b className="text-xs">{p.title}</b>{p.description&&<p className="mt-1 text-[9px] text-zinc-500">{p.description}</p>}</div><span className="text-[9px] text-zinc-500">{p.videoIds.length} vidéos</span></div><div className="mt-2 space-y-1">{p.videoIds.map(id=>{const v=videos.find(x=>x.id===id);return v?<p key={id} className="truncate text-[10px] text-zinc-400">• {v.title}</p>:null})}</div></article>)}</section>}
  {tab==='about'&&<section className="rounded-xl border border-white/10 bg-[#181818] p-4 text-xs text-zinc-300"><p>Chaîne créée semaine 1.</p><p className="mt-2">Réputation : {creator.reputation}/100</p><p className="mt-2">Visage : {creator.showsFace?'visible':'non visible'}</p></section>}
 </div>
}