import type {CreatorProfile,Trend,PublishedVideo} from '../types/game';
interface Props{creator:CreatorProfile;trends:Trend[];videos:PublishedVideo[];rest:()=>void}
const thumb=['https://images.unsplash.com/photo-1542751371-adc38448a05e?w=700&q=80','https://images.unsplash.com/photo-1518770660439-4636190af475?w=700&q=80','https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=700&q=80'];
export default function DashboardScreen({creator,trends,videos,rest}:Props){
 const totalViews=videos.reduce((n,v)=>n+v.views,0),totalSubs=videos.reduce((n,v)=>n+v.subscribersGained,0),totalRevenue=videos.reduce((n,v)=>n+v.revenueGenerated,0);
 const top=[...videos].sort((a,b)=>b.views-a.views).slice(0,3);
 return <div className="space-y-5">
  <div><div className="flex items-center justify-between"><div><h1 className="text-xl font-bold">Accueil</h1><p className="mt-1 text-[11px] text-zinc-500">{creator.name} · semaine {creator.week}</p></div><button onClick={rest} className="rounded-full bg-white px-3 py-1.5 text-[10px] font-bold text-black">Passer une semaine</button></div></div>
  <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-bold">Analytics</h2><span className="text-[10px] text-zinc-500">{videos.length} publiée{videos.length!==1?'s':''}</span></div><div className="grid grid-cols-3 gap-2"><div className="rounded-xl border border-white/10 bg-[#181818] p-3"><p className="text-[9px] text-zinc-500">Vues</p><b className="text-sm">{totalViews.toLocaleString('fr-FR')}</b></div><div className="rounded-xl border border-white/10 bg-[#181818] p-3"><p className="text-[9px] text-zinc-500">Abonnés</p><b className="text-sm">+{totalSubs.toLocaleString('fr-FR')}</b></div><div className="rounded-xl border border-white/10 bg-[#181818] p-3"><p className="text-[9px] text-zinc-500">Revenus</p><b className="text-sm">{totalRevenue.toFixed(2)} €</b></div></div></section>
  <section><h2 className="mb-2 text-sm font-bold">Tes meilleures vidéos</h2>{top.length?<div className="space-y-2">{top.map((v,i)=><div key={v.id} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#181818] p-2"><span className="w-4 text-center text-xs font-bold text-zinc-600">{i+1}</span><img src={v.thumbnail} className="h-12 w-20 rounded-md object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold">{v.title}</p><p className="text-[9px] text-zinc-500">{v.views.toLocaleString('fr-FR')} vues · +{v.subscribersGained} abonnés · {v.velocity.toLocaleString('fr-FR')}/h</p></div></div>)}</div>:<p className="text-xs text-zinc-500">Publie une vidéo pour commencer à voir tes statistiques.</p>}</section>
  <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-bold">Tendances</h2><span className="text-[10px] text-zinc-500">Cette semaine</span></div><div className="grid gap-2">{trends.map((t,i)=><div key={t.id} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#181818] p-3"><span className="w-5 text-center text-xs font-bold text-zinc-600">{i+1}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{t.name}</p><p className="text-[10px] text-zinc-500">{t.category} · intérêt x{t.intensity.toFixed(2)}</p></div></div>)}</div></section>
  <section><h2 className="mb-2 text-sm font-bold">Pour toi</h2><div className="space-y-4">{['Le documentaire gaming que tout le monde regarde','J’ai testé le setup PC le plus absurde','Pourquoi cette série a disparu du web'].map((title,i)=><article key={title}><img src={thumb[i]} className="aspect-video w-full rounded-xl object-cover"/><p className="mt-2 text-xs font-semibold">{title}</p></article>)}</div></section>
 </div>
}