import type { CreatorProfile, Trend } from '../types/game';
interface Props { creator: CreatorProfile; trends: Trend[]; rest: () => void; }
const thumb = ['https://images.unsplash.com/photo-1542751371-adc38448a05e?w=700&q=80','https://images.unsplash.com/photo-1518770660439-4636190af475?w=700&q=80','https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=700&q=80'];
export default function DashboardScreen({ creator, trends, rest }: Props) {
 return <div className="space-y-5">
  <div><div className="flex items-center justify-between"><h1 className="text-xl font-bold">Accueil</h1><button onClick={rest} className="rounded-full bg-white px-3 py-1.5 text-[10px] font-bold text-black">Passer une semaine</button></div><p className="mt-1 text-[11px] text-zinc-500">{creator.name} · réputation {creator.reputation}/100 · ton fil évolue avec ton audience.</p></div>
  <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-bold">Pour toi</h2><span className="text-[10px] text-zinc-500">Selon tes intérêts</span></div><div className="space-y-4">{['Le documentaire gaming que tout le monde regarde','J’ai testé le setup PC le plus absurde','Pourquoi cette série a disparu du web'].map((title,i)=><article key={title}><img src={thumb[i]} className="aspect-video w-full rounded-xl object-cover"/><div className="mt-2 flex gap-2"><div className="h-8 w-8 shrink-0 rounded-full bg-zinc-800"/><div><h3 className="text-xs font-semibold leading-4">{title}</h3><p className="mt-1 text-[10px] text-zinc-500">Créateur virtuel · {i ? 'il y a 4 h' : 'il y a 1 h'}</p></div></div></article>)}</div></section>
  <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-bold">Tendances</h2><span className="text-[10px] text-zinc-500">Cette semaine</span></div><div className="grid gap-2">{trends.map((t,i)=><div key={t.id} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#181818] p-3"><span className="w-5 text-center text-xs font-bold text-zinc-600">{i+1}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{t.name}</p><p className="text-[10px] text-zinc-500">{t.category} · intérêt x{t.intensity.toFixed(2)}</p></div><div className="h-7 w-16 overflow-hidden rounded bg-zinc-900"><div className="mt-4 h-2 w-full bg-zinc-500" style={{transform:`translateX(${(1-t.intensity/2)*20}px)`}}/></div></div>)}</div></section>
 </div>
}
