import { useState } from 'react';
import type { CreatorProfile, CreatorSkills, SkillKey, VideoCategory, VideoFormat, VideoProject, Series } from '../types/game';
interface Props { creator: CreatorProfile; skills: CreatorSkills; skillXp: Record<SkillKey,number>; projects: VideoProject[]; series: Series[]; createProject: (title:string, category:VideoCategory, format:VideoFormat, language:'Français', isSeries:boolean, seriesName:string, thumbnail:string)=>void; workOnProject:(id:string,taskId:string)=>void; advanceTurn:()=>void; publishVideo:(id:string)=>void; toggleFace:()=>void; }
const images=['https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&q=80','https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80','https://images.unsplash.com/photo-1453738773917-9c3eff1db985?w=400&q=80'];
const skillNames:Record<SkillKey,string>={editing:'Montage',writing:'Script',filming:'Caméra',research:'Recherche',thumbnail:'Miniature',audio:'Audio',communication:'Communication',storytelling:'Storytelling',business:'Business'};
export default function StudioScreen({creator,skills,skillXp,projects,series,createProject,workOnProject,advanceTurn,publishVideo,toggleFace}:Props){
 const [title,setTitle]=useState(''); const [category,setCategory]=useState<VideoCategory>('Gaming'); const [format,setFormat]=useState<VideoFormat>('standard'); const [isSeries,setIsSeries]=useState(false); const [seriesName,setSeriesName]=useState(''); const [thumbnail,setThumbnail]=useState(images[0]);
 return <div className="space-y-5">
  <div className="flex items-center justify-between"><div><h1 className="text-xl font-bold">Studio</h1><p className="text-[11px] text-zinc-500">Crée, améliore et gère tes productions.</p></div><button onClick={advanceTurn} className="rounded-full bg-white px-3 py-2 text-[10px] font-bold text-black">Semaine suivante</button></div>
  <section className="rounded-2xl border border-white/10 bg-[#181818] p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold">Nouvelle vidéo</h2><span className="text-[10px] text-zinc-500">{creator.energy} énergie</span></div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Titre de la vidéo" className="mb-3 w-full rounded-lg border border-white/10 bg-black p-3 text-xs outline-none focus:border-white/30"/><div className="grid grid-cols-2 gap-2"><select value={category} onChange={e=>setCategory(e.target.value as VideoCategory)} className="rounded-lg border border-white/10 bg-black p-2 text-xs"><option>Gaming</option><option>Tech</option><option>Documentaire</option><option>Cinéma</option><option>Vlog</option><option>ASMR</option><option>Politique</option></select><select value={format} onChange={e=>setFormat(e.target.value as VideoFormat)} className="rounded-lg border border-white/10 bg-black p-2 text-xs"><option value="short">Short · 1 sem.</option><option value="standard">Standard · 2 sem.</option><option value="documentary">Documentaire · 4 sem.</option><option value="live">Live · 1 sem.</option></select></div><div className="mt-3 rounded-lg border border-white/10 bg-black p-3 text-[10px] text-zinc-400"><b className="text-white">Production : </b>le lancement réserve de l’énergie, puis chaque amélioration consomme aussi de l’énergie. Certaines options se débloquent avec tes compétences.</div><button onClick={()=>setIsSeries(!isSeries)} className={`mt-2 w-full rounded-lg border p-2 text-left text-xs ${isSeries?'border-white/40 bg-zinc-800':'border-white/10 bg-black'}`}>{isSeries?'Série activée':'Vidéo indépendante'} <span className="float-right text-zinc-500">{isSeries?'Nouvel épisode':'One-shot'}</span></button>{isSeries&&<input value={seriesName} onChange={e=>setSeriesName(e.target.value)} placeholder="Nom de la série" className="mt-2 w-full rounded-lg border border-white/10 bg-black p-2 text-xs outline-none"/>}<div className="mt-3 flex gap-2">{images.map(src=><button key={src} onClick={()=>setThumbnail(src)} className={`overflow-hidden rounded-lg border-2 ${thumbnail===src?'border-white':'border-transparent opacity-60'}`}><img src={src} className="h-12 w-20 object-cover"/></button>)}</div><button disabled={!title.trim()} onClick={()=>{createProject(title,category,format,'Français',isSeries,seriesName,thumbnail);setTitle('')}} className="mt-4 w-full rounded-lg bg-white py-2.5 text-xs font-bold text-black disabled:opacity-30">Lancer la production</button></section>
  <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-bold">Compétences</h2><span className="text-[10px] text-zinc-500">Niveaux 1 → 100</span></div><div className="grid grid-cols-3 gap-2">{(Object.keys(skills) as SkillKey[]).map(k=><div key={k} className="rounded-xl border border-white/10 bg-[#181818] p-2"><div className="flex justify-between"><span className="text-[10px] text-zinc-400">{skillNames[k]}</span><b className="text-[10px]">{skills[k]}</b></div><div className="mt-2 h-1 rounded bg-zinc-800"><div className="h-1 rounded bg-white" style={{width:`${Math.min(100,skillXp[k]/(100+skills[k]*7.5)*100)}%`}}/></div></div>)}</div></section>
  <section className="rounded-xl border border-white/10 bg-[#181818] p-3"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold">Présence à l’écran</p><p className="text-[10px] text-zinc-500">{creator.showsFace?'Tu montres ton visage':'Tu restes sans visage'}</p></div><button onClick={toggleFace} className="rounded-full border border-white/15 px-3 py-1.5 text-[10px]">Changer</button></div></section>
  <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-bold">Productions en cours</h2><span className="text-[9px] text-zinc-500">{projects.filter(p=>p.weeksDone>=p.totalWeeks).length} prête(s)</span></div>{projects.length===0?<div className="rounded-xl border border-dashed border-white/10 p-5 text-center text-xs text-zinc-600">Aucun projet en cours.</div>:<div className="space-y-3">{projects.map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-[#181818] p-3"><div className="flex gap-3"><img src={p.thumbnail} className="h-16 w-24 rounded-lg object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{p.title}</p><p className="mt-1 text-[10px] text-zinc-500">{p.category} · {p.isSeries?`Série · épisode ${p.episodeNumber}`:'Indépendante'}</p><div className="mt-2 h-1.5 rounded bg-zinc-800"><div className="h-1.5 rounded bg-white" style={{width:`${p.quality}%`}}/></div><p className="mt-1 text-[9px] text-zinc-500">Qualité {p.quality}/100 · semaine {p.weeksDone}/{p.totalWeeks}</p></div></div><div className="mt-3 grid grid-cols-2 gap-2">{p.tasks.filter(t=>!t.done).map(t=>{const locked=skills[t.skill]<t.requiredLevel; return <button key={t.id} disabled={locked||creator.energy<t.energyCost} onClick={()=>workOnProject(p.id,t.id)} className={`rounded-lg border p-2 text-left text-[10px] ${locked?'border-white/5 bg-zinc-950 opacity-40':'border-white/10 bg-black'} disabled:cursor-not-allowed`}><span className="block font-semibold">{t.label}</span><span className="text-zinc-500">{locked?`Niv. ${t.requiredLevel} requis`:`−${t.energyCost} énergie · +${t.xpGain} XP`}</span></button>})}</div>{p.weeksDone>=p.totalWeeks&&<button onClick={()=>publishVideo(p.id)} className="mt-3 w-full rounded-lg bg-white py-2 text-[10px] font-bold text-black">Publier et découvrir le résultat</button>}</div>)}</div>}</section>
  {series.length>0&&<section><h2 className="mb-2 text-sm font-bold">Tes séries</h2><div className="space-y-2">{series.map(s=><div key={s.id} className="rounded-xl border border-white/10 bg-[#181818] p-3"><div className="flex justify-between"><span className="text-xs font-bold">{s.name}</span><span className="text-[10px] text-zinc-500">Saison {s.season}</span></div><div className="mt-2 grid grid-cols-3 gap-2 text-[9px] text-zinc-500"><span>Popularité <b className="text-white">{Math.round(s.popularity)}</b></span><span>Attente <b className="text-white">{Math.round(s.expectation)}</b></span><span>Fatigue <b className="text-white">{Math.round(s.fatigue)}</b></span></div></div>)}</div></section>}
 </div>
}
